export const DATA_GET_REQUEST = "DATA_GET_REQUEST";
export const DATA_GET_SUCCESS = "DATA_GET_SUCCESS";
export const DATA_GET_FAIL = "DATA_GET_FAIL";
export const SORT_A_Z = "SORT_A_Z";
export const SORT_Z_A = "SORT_Z_A";
export const SEARCH_CONTACT = "SEARCH_CONTACT";
//export const LIKE = "LIKE";
//export const DISLIKE = "DISLIKE";
export const  UPDATE_CONTACT=" UPDATE_CONTACT"
